#Case Study 4 :  Data Science Shark Tank:  Pitch Your Ideas

** Due Date: Dec. 9, before the class**
<a href="https://www.youtube.com/channel/UCxQB1f0fQQEQuh8O-6KCONA"> <img src="https://cp.inkrefuge.com/images%5Cpressreleases/shark%20tank_large.jpg" width="400px"> </a>

After the previous 3 case studies,  your team has now equipped with all the three powerful skills of data science: Hacking skill, Business skill and Math skill. In this project, your team is going to make use of these skills to come up with an idea of a new business/startup based upon data science technology. Your goal is to design a better service/solution on any data you like, develop a prototype/demo and prepare a pitch for your idea.
* Your team needs to decide which business problem is important for the market you are joining in (for example, social media market, housing market, search market, etc.).
* Then design a data science approach to improve one of the current services or design a new service on any data that you choose (hopefully not Yelp dataset again).
* The solution should include all the three components of data science: 1) the business part to analyze the potential impact of your new/improved service, why the idea can make money, how much are you evaluating the company; How are you planing to persuade the sharks to invest in your business; 2) the mathematical part to formulate the problem and develop math solution; 3) the programming part to collect the data, implement the math solution, and develop the prototype/demo.


# Background about Elevator Pitch (90 seconds) and Shark Tank

In [1]:
from IPython.display import YouTubeVideo
YouTubeVideo("mrSmaCo29U4") 

In [2]:
YouTubeVideo("g31M8WmKeqg") 


**Optional Readings:** 
* LinkedIn API: https://developer.linkedin.com/docs/rest-api
* Zillow API: https://pypi.python.org/pypi/pyzillow
* Google Map API: https://developers.google.com/api-client-library/python/apis/mapsengine/v1?hl=en
* More APIs: https://github.com/ptwobrussell/Mining-the-Social-Web-2nd-Edition


** Python libraries you may want to use:**
* Scikit-learn (http://scikit-learn.org): machine learning tools in Python.

** NOTE **
* Please don't forget to save the notebook frequently when working in IPython Notebook, otherwise the changes you made can be lost.

*----------------------

#Problem 1: the Business Part (20 points)
 As a group, learn about the data science related business and research about the current markets: such as search, social media, advertisement, recommendation and so on.
Pick one of the markets for further consideration, and design a new service  which you believe to be important in the market. 
Define precisely in the report and briefly in the cells below, what is the business problem that your team wants to solve.
Why the problem is important to solve? 
Why you believe you could make a big difference with data science technology.
How are you planing to persuade the investors to buy in your idea.

**Please describe here *briefly*  (please edit this cell)**

1) Your business problem to solve:

How to market products for statups or solo sellers on ebay using twitter social network



2) Why the problem is important to solve?

Marketing cost is high and inefficient

Marketing via social network is more reliable and efficient


3) What is your idea to solve the problem? 

Here we just solve the twitter part of our business plan, that is to rank the twitter users according
to their influence indices, which is defiend as the product of their influence in their social network
and the number of their followers.


4) What differences you could make with your data science approach?

A better marketing plan for small business.
Both the sellers and twitter users can benefit from it.


5) Why do you believe the idea deserves the investment of the "sharks"?

Come on. Its $$$ business.





#Problem 2: The Math Part (20 points)

Define the business problem as a math problem and design a math solution to the problem.


**Insert your answers here**


1) Problem formulation in Math:

For the PageRank formula:
<img src="http://localhost:8888/files/pagerank.jpg" width="500px">


For our UserRank formula:
<img src="http://localhost:8888/files/UserRank.png" width="800px">


2) Math Solution:
Since we are dealing with social network data, it is natural to use PageRank Algorithms to assess each candidate's 
influence in his or her social network. Here we just pick the first 10 mutual friends of each candidate, and we ranked 
theses 11 people based on their newtork statuses.


3) Implementation of the Solution
First, you have to transform the collected data to a binary matrix, where each row represents whether or not the twitter user of that row is following the user in column. Then, you can initialize each person's score with any arbitrary values. 
Secondly, you can find the final scores, or the staedy-state distribution of everyone in their little network via iterating over the graph.




#Problem 3: The Hacking Part  (20 points)


* Data Collection
* Implement a small Demo/Prototype/experiment result figures for the "product" of your data science company. You could use this demo during the Pitch

In [115]:
# Import all the packages required

import twitter, io,json
from prettytable import PrettyTable
import sys
import time
from urllib2 import URLError
from httplib import BadStatusLine
from functools import partial
from sys import maxint
import numpy as np
import pandas as pd
import scipy.sparse.linalg as sl

In [2]:
#---------------------------------------------
# Define a Function to Login Twitter API
def oauth_login():
    # Go to http://twitter.com/apps/new to create an app and get values
    # for these credentials that you'll need to provide in place of these
    # empty string values that are defined as placeholders.
    # See https://dev.twitter.com/docs/auth/oauth for more information 
    # on Twitter's OAuth implementation.
    
    CONSUMER_KEY = 'V5s2QI2uyCK2htBIbkT3T34ox'
    CONSUMER_SECRET ='IPgFYZbdlnxJ2QwAtLEkAmKsjMvFQe7KGbajK3Y5bRiBLAd1tF'
    OAUTH_TOKEN = '3062701068-13Ti6kCgN9uN7uvgi8h3CfmyeACWKwokNhBw228'
    OAUTH_TOKEN_SECRET = 'FJyJuSIcPJi2Y4HWqCCMmRvi60wXPWuaHVLpxd6VMT0Yu'
    
    auth = twitter.oauth.OAuth(OAUTH_TOKEN, OAUTH_TOKEN_SECRET, CONSUMER_KEY, CONSUMER_SECRET)
    
    twitter_api = twitter.Twitter(auth=auth)
    return twitter_api

In [13]:
# Function to save the json file into local drive for future reference

def save_json(filename, data):
    with io.open('{0}.json'.format(filename), 
                 'w', encoding='utf-8') as f:
        f.write(unicode(json.dumps(data, ensure_ascii=False)))

# Function to load the json file from local drive

def load_json(filename):
    with io.open('{0}.json'.format(filename), 
                 encoding='utf-8') as f:
        return f.read()

# Making a preety table 
    
def make_table(label,data,count=maxint):
    pt = PrettyTable(field_names=[label[0],label[1]])
    for r in data:
        if r[0] =='':continue
        pt.add_row([r[0],r[1]])
        pt.align[label[0]], pt.align[label[1]] = 'c', 'r' # Set column alignment
    print pt
    return

In [4]:
twitter_api = oauth_login()

In [8]:
#----------------------------------------------
# Your code starts here
#   Please add comments or text cells in between to explain the general idea of each block of the code.
#   Please feel free to add more cells below this cell if necessary
def make_twitter_request(twitter_api_func, max_errors=10, *args, **kw):
    def handle_twitter_http_error(e, wait_period=2, sleep_when_rate_limited=True):
        if wait_period > 3600: # Seconds
            print >> sys.stderr, 'Too many retries. Quitting.'
            raise e
        if e.e.code == 401:
            print >> sys.stderr, 'Encountered 401 Error (Not Authorized)'
            return None
        elif e.e.code == 404:
            print >> sys.stderr, 'Encountered 404 Error (Not Found)'
            return None
        elif e.e.code == 429:
            print >> sys.stderr, 'Encountered 429 Error (Rate Limit Exceeded)'
            if sleep_when_rate_limited:
                print >> sys.stderr, "Retrying in 15 minutes...ZzZ..."
                sys.stderr.flush()
                time.sleep(60*15 + 5)
                print >> sys.stderr, '...ZzZ...Awake now and trying again.'
                return 2
            else:
                raise e # Caller must handle the rate limiting issue
        elif e.e.code in (500, 502, 503, 504):
            print >> sys.stderr, 'Encountered %i Error. Retrying in %i seconds' % \
            (e.e.code, wait_period)
            time.sleep(wait_period)
            wait_period *= 1.5
            return wait_period
        else:
            raise e 
    wait_period = 2
    error_count = 0
    while True:
        try:
            return twitter_api_func(*args, **kw)
        except twitter.api.TwitterHTTPError, e:
            error_count = 0
            wait_period = handle_twitter_http_error(e, wait_period)
            if wait_period is None:
                return
        except URLError, e:
            error_count += 1
            print >> sys.stderr, "URLError encountered. Continuing."
            if error_count > max_errors:
                print >> sys.stderr, "Too many consecutive errors...bailing out."
                raise
        except BadStatusLine, e:
            error_count += 1
            print >> sys.stderr, "BadStatusLine encountered. Continuing."
            if error_count > max_errors:
                print >> sys.stderr, "Too many consecutive errors...bailing out."
                raise


def get_friends_followers(twitter_api, screen_name=None, user_id=None,
                          limit=maxint, fr_or_fl = True,plimit = 100):
    assert(screen_name !=None) != (user_id != None),"Must have screen_name or user_id, but not both"
    if (fr_or_fl):
        get_ids = partial(make_twitter_request, twitter_api.friends.ids,
                              count=plimit)
        label = "friends"
    else:
        get_ids = partial(make_twitter_request, twitter_api.followers.ids,
                                count=plimit)
        label = "followers"
    result_ids = []
    if limit == 0:return
    cursor = -1
    while cursor !=0:
        if screen_name:
            response = get_ids(screen_name = screen_name, cursor = cursor)
        else:
            response = get_ids(user_id=user_id, cursor=cursor)
        if response is not None:
            result_ids += response['ids']
            cursor = response['next_cursor']
        print >> sys.stderr, 'Fetched {0} total {1} ids for {2}'.format(len(result_ids),label, (user_id or screen_name))
        if len(result_ids) >= limit or response is None:
            break
    return result_ids[:limit]


friends_ids = get_friends_followers(twitter_api,screen_name="Nike",limit=50,
                                                   fr_or_fl=True,plimit = 100)
followers_ids = get_friends_followers(twitter_api,screen_name="Nike",limit=5000,
                                                   fr_or_fl = False,plimit = 5000)

Fetched 100 total friends ids for Nike
Fetched 5000 total followers ids for Nike


In [18]:
filtered_list = []
count = 0
# First , we filter all people that have a follower ration bigger than 1.2
twitter_func = partial(make_twitter_request, twitter_api.users.lookup,
                                    count=5000)
for i in range(0,50):
    tmp = twitter_func(user_id = followers_ids[i*100:(i+1)*100],include_user_entities = True)
    r = [u['id'] for u in tmp if 1.0*u['followers_count']/u['friends_count'] > 1.2]
    if len(filtered_list) + len(r) > 200:
        break
    else:
        filtered_list += r
filtered_list

[339530251,
 1451390232,
 310441671,
 446410553,
 20188504,
 49565686,
 618811816,
 28764917,
 1632755064,
 459570927,
 56337471,
 945012014,
 53447067,
 794087815,
 214584456,
 737183868,
 267061023,
 551046830,
 477442986,
 1888986979,
 244873413,
 766231346,
 241199445,
 1129951758,
 929532036,
 246846985,
 330091517,
 708210458,
 251828373,
 1275811220,
 275590213,
 231305294,
 124624985,
 992140022,
 219332006,
 509288969,
 28324031,
 625067973,
 1570847064,
 1973989417,
 620331987,
 329077339,
 146340115,
 1040847247,
 111588847,
 594012180,
 1523445073,
 158434306,
 428702574,
 150513051,
 1527529573,
 265668224,
 36888495,
 502002243,
 527029384,
 451200505,
 983061145,
 768456416,
 340775765,
 1707547963,
 1024309291,
 267332736,
 1720971487,
 1538897461,
 63382216,
 490983789,
 732406159,
 1727022103,
 855614892,
 701935932,
 570093647,
 1099400719,
 602936723,
 21808524,
 1264524391,
 384971109,
 516564029,
 559720576,
 824334727,
 52253739,
 395610814,
 371513766,
 10119186

In [19]:
len(filtered_list)

182

In [20]:
network_ids= {}
for id in filtered_list:
    print 'now',id
    ffs = get_friends_followers(twitter_api,user_id = id,limit=5000,fr_or_fl=True,plimit = 5000)
    fo_ids = get_friends_followers(twitter_api,user_id = id,limit=5000,fr_or_fl=False,plimit = 5000)
    s = set(ffs).intersection(set(fo_ids))
    cids=[]
    for i in range(0,len(ffs) / 100):
        tmp = twitter_func(user_id = ffs[i*100:(i+1)*100],include_user_entities = True)
        rs = [u['id'] for u in tmp]
        if (len(rs) > 0):
            for r in rs:
                if (r in s and r != filtered_list[1]):
                    cids.append(r)
            break
    for i in range(0,len(fo_ids) / 100):
        tmp = twitter_func(user_id = fo_ids[i*100:(i+1)*100],include_user_entities = True)
        rs = [u['id'] for u in tmp]
        if (len(rs) > 0):
            for r in rs:
                if (r in s and r != filtered_list[1]):
                    cids.append(r)
            break
    network_ids[id] = cids
    
    

Fetched 387 total friends ids for 339530251
Fetched 527 total followers ids for 339530251

now 339530251
now


Fetched 433 total friends ids for 1451390232
Fetched 1382 total followers ids for 1451390232

 1451390232
now


Fetched 9 total friends ids for 310441671
Fetched 14 total followers ids for 310441671

 310441671
now


Fetched 65 total friends ids for 446410553
Fetched 116 total followers ids for 446410553

 446410553
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 20188504
Encountered 401 Error (Not Authorized)

 20188504
now


Fetched 0 total followers ids for 20188504
Fetched 66 total friends ids for 49565686
Fetched 114 total followers ids for 49565686

 49565686
now


Fetched 159 total friends ids for 618811816
Fetched 2378 total followers ids for 618811816

 618811816
now


Fetched 839 total friends ids for 28764917
Fetched 5000 total followers ids for 28764917

 28764917
now


Fetched 333 total friends ids for 1632755064
Fetched 510 total followers ids for 1632755064

 1632755064
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Fetched 25 total friends ids for 459570927
Fetched 5000 total followers ids for 459570927

 459570927
now


Fetched 386 total friends ids for 56337471
Fetched 574 total followers ids for 56337471

 56337471
now


Fetched 59 total friends ids for 945012014
Fetched 104 total followers ids for 945012014

 945012014
now


Fetched 114 total friends ids for 53447067
Fetched 354 total followers ids for 53447067

 53447067
now


Fetched 443 total friends ids for 794087815
Fetched 1753 total followers ids for 794087815

 794087815
now


Fetched 30 total friends ids for 214584456
Fetched 179 total followers ids for 214584456

 214584456
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 737183868
Encountered 401 Error (Not Authorized)

 737183868
now


Fetched 0 total followers ids for 737183868
Fetched 743 total friends ids for 267061023
Fetched 2717 total followers ids for 267061023

 267061023
now


Fetched 200 total friends ids for 551046830
Fetched 592 total followers ids for 551046830

 551046830
now


Fetched 900 total friends ids for 477442986
Fetched 1394 total followers ids for 477442986

 477442986
now


Fetched 346 total friends ids for 1888986979
Fetched 468 total followers ids for 1888986979

 1888986979
now


Fetched 666 total friends ids for 244873413
Fetched 5000 total followers ids for 244873413

 244873413
now


Fetched 16 total friends ids for 766231346
Fetched 98 total followers ids for 766231346

 766231346
now


Fetched 467 total friends ids for 241199445
Fetched 566 total followers ids for 241199445

 241199445
now


Fetched 130 total friends ids for 1129951758
Fetched 291 total followers ids for 1129951758

 1129951758
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 929532036
Encountered 401 Error (Not Authorized)

 929532036
now


Fetched 0 total followers ids for 929532036
Fetched 79 total friends ids for 246846985
Fetched 4471 total followers ids for 246846985

 246846985
now


Fetched 294 total friends ids for 330091517
Fetched 740 total followers ids for 330091517

 330091517
now


Fetched 95 total friends ids for 708210458
Fetched 227 total followers ids for 708210458

 708210458
now


Fetched 128 total friends ids for 251828373
Fetched 194 total followers ids for 251828373

 251828373
now


Fetched 879 total friends ids for 1275811220
Fetched 5000 total followers ids for 1275811220

 1275811220
now


Fetched 298 total friends ids for 275590213
Fetched 603 total followers ids for 275590213

 275590213
now


Fetched 310 total friends ids for 231305294
Fetched 534 total followers ids for 231305294

 231305294
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 124624985
Encountered 401 Error (Not Authorized)

 124624985
now


Fetched 0 total followers ids for 124624985
Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 992140022
Encountered 401 Error (Not Authorized)

 992140022
now


Fetched 0 total followers ids for 992140022
Fetched 201 total friends ids for 219332006
Fetched 370 total followers ids for 219332006

 219332006
now


Fetched 148 total friends ids for 509288969
Fetched 358 total followers ids for 509288969

 509288969
now


Fetched 502 total friends ids for 28324031
Fetched 2420 total followers ids for 28324031

 28324031
now


Fetched 352 total friends ids for 625067973
Fetched 1066 total followers ids for 625067973

 625067973
now


Fetched 275 total friends ids for 1570847064
Fetched 1000 total followers ids for 1570847064

 1570847064
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 1973989417
Encountered 401 Error (Not Authorized)

 1973989417
now


Fetched 0 total followers ids for 1973989417
Fetched 170 total friends ids for 620331987
Fetched 259 total followers ids for 620331987

 620331987
now


Fetched 359 total friends ids for 329077339
Fetched 747 total followers ids for 329077339

 329077339
now


Fetched 103 total friends ids for 146340115
Fetched 161 total followers ids for 146340115

 146340115
now


Fetched 100 total friends ids for 1040847247
Fetched 166 total followers ids for 1040847247

 1040847247
now


Fetched 310 total friends ids for 111588847
Fetched 390 total followers ids for 111588847

 111588847
now


Fetched 312 total friends ids for 594012180
Fetched 5000 total followers ids for 594012180

 594012180
now


Fetched 105 total friends ids for 1523445073
Fetched 133 total followers ids for 1523445073

 1523445073
now


Fetched 96 total friends ids for 158434306
Fetched 546 total followers ids for 158434306

 158434306
now


Fetched 29 total friends ids for 428702574
Fetched 236 total followers ids for 428702574

 428702574
now


Fetched 936 total friends ids for 150513051
Fetched 2008 total followers ids for 150513051

 150513051
now


Fetched 79 total friends ids for 1527529573
Fetched 165 total followers ids for 1527529573

 1527529573
now


Fetched 5000 total friends ids for 265668224
Fetched 5000 total followers ids for 265668224

 265668224
now


Fetched 2734 total friends ids for 36888495
Fetched 5000 total followers ids for 36888495

 36888495
now


Fetched 171 total friends ids for 502002243
Fetched 238 total followers ids for 502002243

 502002243
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Fetched 382 total friends ids for 527029384
Fetched 5000 total followers ids for 527029384

 527029384
now


Fetched 2525 total friends ids for 451200505
Fetched 5000 total followers ids for 451200505

 451200505
now


Fetched 720 total friends ids for 983061145
Fetched 991 total followers ids for 983061145

 983061145
now


Fetched 145 total friends ids for 768456416
Fetched 224 total followers ids for 768456416

 768456416
now


Fetched 318 total friends ids for 340775765
Fetched 454 total followers ids for 340775765

 340775765
now


Fetched 2 total friends ids for 1707547963
Fetched 23 total followers ids for 1707547963

 1707547963
now


Fetched 235 total friends ids for 1024309291
Fetched 402 total followers ids for 1024309291

 1024309291
now


Fetched 3516 total friends ids for 267332736
Fetched 5000 total followers ids for 267332736

 267332736
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 1720971487
Encountered 401 Error (Not Authorized)

 1720971487
now


Fetched 0 total followers ids for 1720971487
Fetched 1846 total friends ids for 1538897461
Fetched 2411 total followers ids for 1538897461

 1538897461
now


Fetched 487 total friends ids for 63382216
Fetched 2266 total followers ids for 63382216

 63382216
now


Fetched 327 total friends ids for 490983789
Fetched 395 total followers ids for 490983789

 490983789
now


Fetched 570 total friends ids for 732406159
Fetched 2124 total followers ids for 732406159

 732406159
now


Fetched 121 total friends ids for 1727022103
Fetched 163 total followers ids for 1727022103

 1727022103
now


Fetched 355 total friends ids for 855614892
Fetched 452 total followers ids for 855614892

 855614892
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Fetched 899 total friends ids for 701935932
Fetched 1341 total followers ids for 701935932

 701935932
now


Fetched 857 total friends ids for 570093647
Fetched 5000 total followers ids for 570093647

 570093647
now


Fetched 117 total friends ids for 1099400719
Fetched 206 total followers ids for 1099400719

 1099400719
now


Fetched 136 total friends ids for 602936723
Fetched 200 total followers ids for 602936723

 602936723
now


Fetched 203 total friends ids for 21808524
Fetched 586 total followers ids for 21808524

 21808524
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 1264524391
Encountered 401 Error (Not Authorized)

 1264524391
now


Fetched 0 total followers ids for 1264524391
Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 384971109
Encountered 401 Error (Not Authorized)

 384971109
now


Fetched 0 total followers ids for 384971109
Fetched 177 total friends ids for 516564029
Fetched 248 total followers ids for 516564029

 516564029
now


Fetched 253 total friends ids for 559720576
Fetched 1152 total followers ids for 559720576

 559720576
now


Fetched 481 total friends ids for 824334727
Fetched 764 total followers ids for 824334727

 824334727
now


Fetched 458 total friends ids for 52253739
Fetched 2688 total followers ids for 52253739

 52253739
now


Fetched 452 total friends ids for 395610814
Fetched 941 total followers ids for 395610814

 395610814
now


Fetched 46 total friends ids for 371513766
Fetched 248 total followers ids for 371513766

 371513766
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 1011918631
Encountered 401 Error (Not Authorized)

 1011918631
now


Fetched 0 total followers ids for 1011918631
Fetched 204 total friends ids for 179575702
Fetched 272 total followers ids for 179575702

 179575702
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Fetched 210 total friends ids for 201044265
Fetched 2510 total followers ids for 201044265

 201044265
now


Fetched 499 total friends ids for 35752213
Fetched 738 total followers ids for 35752213

 35752213
now


Fetched 86 total friends ids for 26823482
Fetched 625 total followers ids for 26823482

 26823482
now


Fetched 747 total friends ids for 22793219
Fetched 1498 total followers ids for 22793219

 22793219
now


Fetched 36 total friends ids for 1764602790
Fetched 49 total followers ids for 1764602790

 1764602790
now


Fetched 117 total friends ids for 1155290534
Fetched 176 total followers ids for 1155290534

 1155290534
now


Fetched 1462 total friends ids for 277503620
Fetched 2566 total followers ids for 277503620

 277503620
now


Fetched 190 total friends ids for 1508062062
Fetched 907 total followers ids for 1508062062

 1508062062
now


Fetched 490 total friends ids for 1603957356
Fetched 636 total followers ids for 1603957356

 1603957356
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 172366463
Encountered 401 Error (Not Authorized)

 172366463
now


Fetched 0 total followers ids for 172366463
Fetched 770 total friends ids for 562240610
Fetched 1305 total followers ids for 562240610

 562240610
now


Fetched 349 total friends ids for 257997785
Fetched 634 total followers ids for 257997785

 257997785
now


Fetched 979 total friends ids for 171664883
Fetched 3931 total followers ids for 171664883

 171664883
now


Fetched 472 total friends ids for 310702244
Fetched 577 total followers ids for 310702244

 310702244
now


Fetched 194 total friends ids for 737768076
Fetched 240 total followers ids for 737768076

 737768076
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Fetched 137 total friends ids for 243854382
Fetched 278 total followers ids for 243854382

 243854382
now


Fetched 435 total friends ids for 24796874
Fetched 977 total followers ids for 24796874

 24796874
now


Fetched 354 total friends ids for 1438356349
Fetched 456 total followers ids for 1438356349

 1438356349
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 1030238041
Encountered 401 Error (Not Authorized)

 1030238041
now


Fetched 0 total followers ids for 1030238041
Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 940624669
Encountered 401 Error (Not Authorized)

 940624669
now


Fetched 0 total followers ids for 940624669
Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 1630344410
Encountered 401 Error (Not Authorized)

 1630344410
now


Fetched 0 total followers ids for 1630344410
Fetched 303 total friends ids for 271601301
Fetched 518 total followers ids for 271601301

 271601301
now


Fetched 3350 total friends ids for 340360397
Fetched 5000 total followers ids for 340360397

 340360397
now


Fetched 242 total friends ids for 1855943461
Fetched 298 total followers ids for 1855943461

 1855943461
now


Fetched 87 total friends ids for 997259587
Fetched 112 total followers ids for 997259587

 997259587
now


Fetched 10 total friends ids for 161124913
Fetched 17 total followers ids for 161124913

 161124913
now


Fetched 44 total friends ids for 432500173
Fetched 167 total followers ids for 432500173

 432500173
now


Fetched 294 total friends ids for 364918201
Fetched 356 total followers ids for 364918201

 364918201
now


Fetched 23 total friends ids for 117479000
Fetched 46 total followers ids for 117479000

 117479000
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 259475565
Encountered 401 Error (Not Authorized)

 259475565
now


Fetched 0 total followers ids for 259475565
Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Fetched 1014 total friends ids for 43112027
Fetched 5000 total followers ids for 43112027

 43112027
now


Fetched 210 total friends ids for 36063241
Fetched 574 total followers ids for 36063241

 36063241
now


Fetched 850 total friends ids for 555896063
Fetched 1518 total followers ids for 555896063

 555896063
now


Fetched 38 total friends ids for 15370140
Fetched 297 total followers ids for 15370140

 15370140
now


Fetched 619 total friends ids for 366970852
Fetched 1912 total followers ids for 366970852

 366970852
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 829136064
Encountered 401 Error (Not Authorized)

 829136064
now


Fetched 0 total followers ids for 829136064
Fetched 63 total friends ids for 618867618
Fetched 89 total followers ids for 618867618

 618867618
now


Fetched 7 total friends ids for 1864435375
Fetched 141 total followers ids for 1864435375

 1864435375
now


Fetched 231 total friends ids for 608158960
Fetched 290 total followers ids for 608158960

 608158960
now


Fetched 77 total friends ids for 909949416
Fetched 142 total followers ids for 909949416

 909949416
now


Fetched 50 total friends ids for 1447491636
Fetched 63 total followers ids for 1447491636

 1447491636
now


Fetched 228 total friends ids for 1248962900
Fetched 298 total followers ids for 1248962900

 1248962900
now


Fetched 28 total friends ids for 365182442
Fetched 51 total followers ids for 365182442

 365182442
now


Fetched 4 total friends ids for 43597940
Fetched 8 total followers ids for 43597940

 43597940
now


Encountered 401 Error (Not Authorized)
Fetched 0 total friends ids for 1967754458
Encountered 401 Error (Not Authorized)

 1967754458
now


Fetched 0 total followers ids for 1967754458
Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Fetched 343 total friends ids for 1621683715
Fetched 428 total followers ids for 1621683715

 1621683715
now


Fetched 744 total friends ids for 382446449
Fetched 1601 total followers ids for 382446449

 382446449
now


Fetched 396 total friends ids for 1023996530
Fetched 635 total followers ids for 1023996530

 1023996530
now


Fetched 129 total friends ids for 278147874
Fetched 355 total followers ids for 278147874

 278147874
now


Fetched 304 total friends ids for 1877021646
Fetched 393 total followers ids for 1877021646

 1877021646
now


Fetched 281 total friends ids for 263277317
Fetched 358 total followers ids for 263277317

 263277317
now


Fetched 147 total friends ids for 778984993
Fetched 520 total followers ids for 778984993

 778984993
now


Fetched 483 total friends ids for 447984414
Fetched 657 total followers ids for 447984414

 447984414
now


Fetched 187 total friends ids for 241808522
Fetched 252 total followers ids for 241808522

 241808522
now


Fetched 5000 total friends ids for 86294875
Fetched 5000 total followers ids for 86294875

 86294875
now


Fetched 442 total friends ids for 809871715
Fetched 538 total followers ids for 809871715

 809871715
now


Fetched 369 total friends ids for 123435131
Fetched 493 total followers ids for 123435131

 123435131
now


Fetched 161 total friends ids for 35096092
Fetched 255 total followers ids for 35096092

 35096092
now


Fetched 44 total friends ids for 497752640
Fetched 95 total followers ids for 497752640

 497752640
now


Fetched 213 total friends ids for 1876869842
Fetched 265 total followers ids for 1876869842

 1876869842
now


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
URLError encountered. Continuing.
URLError encountered. Continuing.
URLError encountered. Continuing.
URLError encountered. Continuing.
URLError encountered. Continuing.
URLError encountered. Continuing.
URLError encountered. Continuing.
URLError encountered. Continuing.

 257850075



URLError encountered. Continuing.
URLError encountered. Continuing.
URLError encountered. Continuing.
Too many consecutive errors...bailing out.


URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [21]:
save_json("network_ids",network_ids)

In [25]:
further_filtered  = [(u,len(network_ids[u])) for u in network_ids.keys() if len(network_ids[u])<10 and len(network_ids[u]) > 0]
further_filtered = [f[0] for f in further_filtered]

In [27]:
len(further_filtered)

21

In [55]:
user_id = 541907609
ffs = get_friends_followers(twitter_api,user_id = user_id,limit=5000,fr_or_fl=True,plimit = 5000)
fo_ids = get_friends_followers(twitter_api,user_id = user_id,limit=5000,fr_or_fl=False,plimit = 5000)
s = set(ffs).intersection(set(fo_ids))


Fetched 215 total friends ids for 541907609
Fetched 318 total followers ids for 541907609


In [216]:
def arc(i,reference):
    #A function for finding friends
    result = []
    ffs = get_friends_followers(twitter_api,user_id = i,limit=5000,fr_or_fl=True,plimit = 5000)
    for i in range(0,len(ffs) / 100):
            tmp = twitter_func(user_id = ffs[i*100:(i+1)*100],include_user_entities = True)
            if (len(tmp) > 0):
                for r in tmp:
                    if (r['id'] in reference and r['id'] != i): #Someone that a mutual friend is following is my mutual friend
                        result.append((r['id'],r['friends_count'],r['followers_count']))
    return result
                  

def get_network_scores(user_id,init,frac):
    #First thing to do is to limit the search span
    ffs = get_friends_followers(twitter_api,user_id = user_id,limit=5000,fr_or_fl=True,plimit = 5000)
    fo_ids = get_friends_followers(twitter_api,user_id = user_id,limit=5000,fr_or_fl=False,plimit = 5000)
    mutual_friends = list(set(ffs).intersection(set(fo_ids)))[:init]
    print "now constructing graphs"
    graph = construct_graph(mutual_friends,user_id)
    #print "now collecting scores"
     ##Calculating base scores and flatten Score dictionary
    #scores = {}
    #vector = []
    #for i in graph.columns.values.tolist():
        #u = twitter_api.users.show(user_id = i,include_user_entities = True)
        #scores[i] = 1.0 * u['followers_count'] / u['friends_count']
        #vector.append(scores[i])
        #print >> sys.stderr, 'Fetched Scores for {0}'.format(i)
    #Normalization
    for i in graph.index:
        n = sum(graph.loc[:,i])
        graph.loc[:,i] = 1.0 * graph.loc[:,i] / n
    rank_score = get_ranks(graph,frac)
    return (user_id, rank_score, graph.index)
    #if method == "Prank":
    #    return (user_id,rank_score[0])
    #else:
    #    return (user_id,rank_score[1])

def get_ranks(graph,frac):
    matrix = pd.DataFrame.as_matrix(graph) * frac
    np.fill_diagonal(matrix, 1 - frac)
    print matrix
    #ranks = np.linalg.inv(np.transpose(matrix) -  np.eye(matrix.shape[0])).dot(vector)
    #ranks - min(ranks)
    err = 1
    vector = [1.0 / len(matrix)] * len(matrix)
    oldm = np.asarray(vector)
    count = 0
    while (err > 1e-4 and count <100):
        newm = oldm.dot(np.transpose(matrix))
        err = np.linalg.norm(newm - oldm)
        oldm = newm
        count = count +1
    prank = oldm
    return prank
    
    
def construct_graph(mutual_friends,user_id):
    allids = mutual_friends
    allids.append(user_id)
    graph = pd.DataFrame(0, index = allids,columns = allids)
    get_r = partial(make_twitter_request, twitter_api.friendships.show,count=5000)
    graph.loc[:,user_id] = 1
    graph.loc[user_id,:] = 1
    graph.loc[user_id,user_id] = 0
    #Now looping the realtionships to construct the graph
    i = 0
    while (i < len(mutual_friends)):
        for otid in mutual_friends[i:]:
            tmp = get_r(source_id = mutual_friends[i],target_id = otid)
            if tmp is not None:
                if (tmp['relationship']['source']['followed_by'] == True):
                    graph.loc[otid,mutual_friends[i]] = 1
                if (tmp['relationship']['source']['following'] == True):
                    graph.loc[mutual_friends[i],otid] = 1
        print >> sys.stderr, 'Graph Construction for {0} is finished'.format(mutual_friends[i])
        i = i + 1
    return graph

In [240]:
scores = {}
for i in further_filtered:
    u = twitter_api.users.show(user_id = i,include_user_entities = True)
    scores[i] = 1.0 * u['followers_count'] / u['friends_count']
    print >> sys.stderr, 'Fetched Scores for {0}'.format(i)


result = {}
for i in further_filtered:
    tmp = get_network_scores(i, 10, 0.85)
    result[tmp[0]] = tmp[1] * scores[tmp[0]]
    

Fetched Scores for 158434306
Fetched Scores for 22793219
Fetched Scores for 246846985
Fetched Scores for 778984993
Fetched Scores for 43112027
Fetched Scores for 559720576
Fetched Scores for 570093647
Fetched Scores for 1527529573
Fetched Scores for 214584456
Fetched Scores for 1864435375
Fetched Scores for 244873413
Fetched Scores for 63382216
Fetched Scores for 608158960
Fetched Scores for 267061023
Fetched Scores for 945012014
Fetched Scores for 36063241
Fetched Scores for 428702574
Fetched Scores for 271601301
Fetched Scores for 15370140
Fetched Scores for 432500173
Fetched Scores for 371513766
Fetched 96 total friends ids for 158434306
Fetched 546 total followers ids for 158434306
Graph Construction for 29388032 is finished
Graph Construction for 204211584 is finished
Graph Construction for 30281157 is finished
Graph Construction for 124294412 is finished
Graph Construction for 53819921 is finished
Graph Construction for 46157970 is finished
Graph Construction for 121313046 is fin

now constructing graphs
[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.          0.          0.          0.28333333
   0.          0.          0.          0.          0.085     ]
 [ 0.          0.          0.15        0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.425       0.15        0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.15        0.28333333
   0.          0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.425       0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.  


Fetched 747 total friends ids for 22793219
Fetched 1499 total followers ids for 22793219


now constructing graphs


Graph Construction for 198248449 is finished
Graph Construction for 14379528 is finished
Graph Construction for 22111990 is finished
Graph Construction for 223714564 is finished
Graph Construction for 271558171 is finished
Graph Construction for 17624325 is finished
Graph Construction for 66465746 is finished
Graph Construction for 14497313 is finished
Graph Construction for 33996834 is finished
Graph Construction for 2362778971 is finished
Graph Construction for 22793219 is finished


[[ 0.15   0.     0.     0.     0.     0.     0.     0.     0.     0.     0.085]
 [ 0.     0.15   0.     0.     0.     0.     0.     0.     0.     0.     0.085]
 [ 0.     0.     0.15   0.     0.     0.     0.     0.     0.     0.     0.085]
 [ 0.     0.     0.     0.15   0.     0.     0.     0.425  0.     0.     0.085]
 [ 0.     0.     0.     0.     0.15   0.     0.     0.     0.     0.     0.085]
 [ 0.     0.     0.     0.     0.     0.15   0.     0.     0.425  0.     0.085]
 [ 0.     0.     0.     0.     0.     0.     0.15   0.     0.     0.     0.085]
 [ 0.     0.     0.     0.     0.     0.     0.     0.15   0.     0.     0.085]
 [ 0.     0.     0.     0.     0.     0.425  0.     0.     0.15   0.     0.085]
 [ 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.15
   0.085]
 [ 0.85   0.85   0.85   0.85   0.85   0.425  0.85   0.425  0.425  0.85
   0.15 ]]


Fetched 79 total friends ids for 246846985
Fetched 4472 total followers ids for 246846985


now constructing graphs


Graph Construction for 82837601 is finished
Graph Construction for 1685784325 is finished
Graph Construction for 539692747 is finished
Graph Construction for 1725715981 is finished
Graph Construction for 508809549 is finished
Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Graph Construction for 54181232 is finished
Graph Construction for 119829202 is finished
Graph Construction for 1346337811 is finished
Graph Construction for 126581655 is finished
Graph Construction for 1467978488 is finished
Graph Construction for 246846985 is finished


[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.          0.          0.28333333  0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.15        0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.15        0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.425       0.          0.          0.15        0.425       0.
   0.          0.          0.          0.085     ]
 [ 0.425       0.          0.425       0.          0.28333333  0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.15        0


Fetched 147 total friends ids for 778984993
Fetched 519 total followers ids for 778984993


now constructing graphs


Graph Construction for 1189292256 is finished
Graph Construction for 293483941 is finished
Graph Construction for 412450570 is finished
Graph Construction for 2362765929 is finished
Graph Construction for 247732938 is finished
Graph Construction for 453868947 is finished
Graph Construction for 2713374769 is finished
Graph Construction for 554663442 is finished
Graph Construction for 288769407 is finished
Graph Construction for 768943615 is finished
Graph Construction for 778984993 is finished


[[ 0.15        0.17        0.          0.          0.          0.
   0.12142857  0.14166667  0.10625     0.          0.085     ]
 [ 0.17        0.15        0.          0.          0.2125      0.
   0.12142857  0.          0.          0.425       0.085     ]
 [ 0.          0.          0.15        0.          0.2125      0.          0.
   0.14166667  0.10625     0.          0.085     ]
 [ 0.          0.          0.          0.15        0.          0.
   0.12142857  0.          0.10625     0.          0.085     ]
 [ 0.          0.17        0.2125      0.          0.15        0.          0.
   0.          0.10625     0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.15
   0.12142857  0.14166667  0.10625     0.          0.085     ]
 [ 0.17        0.17        0.          0.          0.          0.28333333
   0.15        0.14166667  0.10625     0.          0.085     ]
 [ 0.17        0.          0.2125      0.          0.          0.28333333
   0.1214285


Fetched 1014 total friends ids for 43112027
Fetched 5000 total followers ids for 43112027


now constructing graphs


Graph Construction for 363656987 is finished
Graph Construction for 305289369 is finished
Graph Construction for 2891457763 is finished
Graph Construction for 2668458014 is finished
Graph Construction for 590178705 is finished
Graph Construction for 43112027 is finished


[[ 0.15  0.    0.    0.    0.    0.17]
 [ 0.    0.15  0.    0.    0.    0.17]
 [ 0.    0.    0.15  0.    0.    0.17]
 [ 0.    0.    0.    0.15  0.    0.17]
 [ 0.    0.    0.    0.    0.15  0.17]
 [ 0.85  0.85  0.85  0.85  0.85  0.15]]


Fetched 253 total friends ids for 559720576
Fetched 1150 total followers ids for 559720576


now constructing graphs


Graph Construction for 3381555328 is finished
Graph Construction for 4165639169 is finished
Encountered 401 Error (Not Authorized)
Graph Construction for 4040894597 is finished
Graph Construction for 373064710 is finished
Graph Construction for 3342614410 is finished
Graph Construction for 3423960807 is finished
Graph Construction for 2741678357 is finished
Graph Construction for 2770576150 is finished
Graph Construction for 410151236 is finished
Graph Construction for 2881446172 is finished
Graph Construction for 559720576 is finished


[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.          0.          0.28333333  0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.28333333  0.15        0.          0.28333333  0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.15        0.          0.          0.
   0.          0.          0.425       0.085     ]
 [ 0.          0.28333333  0.425       0.          0.15        0.          0.425
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.15      


Fetched 464 total friends ids for 570093647
Fetched 5000 total followers ids for 570093647


now constructing graphs


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Graph Construction for 21577728 is finished
Graph Construction for 3253986318 is finished
Graph Construction for 6572632 is finished
Graph Construction for 394568451 is finished
Graph Construction for 61003804 is finished
Graph Construction for 11059232 is finished
Graph Construction for 424757797 is finished
Graph Construction for 72122407 is finished
Graph Construction for 2485343272 is finished
Graph Construction for 1532436524 is finished
Graph Construction for 570093647 is finished


[[ 0.15        0.          0.          0.          0.28333333  0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.          0.12142857  0.          0.2125      0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.15        0.12142857  0.          0.          0.
   0.          0.14166667  0.          0.085     ]
 [ 0.          0.28333333  0.28333333  0.15        0.28333333  0.2125      0.
   0.          0.14166667  0.28333333  0.085     ]
 [ 0.425       0.          0.          0.12142857  0.15        0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.28333333  0.          0.12142857  0.          0.15        0.
   0.          0.14166667  0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.14166667  0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.15        0


Fetched 86 total friends ids for 1527529573
Fetched 165 total followers ids for 1527529573


now constructing graphs


Graph Construction for 248364800 is finished
Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Graph Construction for 3193776769 is finished
Graph Construction for 4074799874 is finished
Graph Construction for 2198960264 is finished
Graph Construction for 2364128017 is finished
Graph Construction for 3224030612 is finished
Graph Construction for 1272305173 is finished
Graph Construction for 3064682263 is finished
Encountered 401 Error (Not Authorized)
Graph Construction for 2469097200 is finished
Graph Construction for 2517793825 is finished
Graph Construction for 1527529573 is finished


[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.          0.17        0.17        0.          0.
   0.425       0.          0.17        0.085     ]
 [ 0.          0.          0.15        0.          0.          0.
   0.28333333  0.          0.          0.          0.085     ]
 [ 0.          0.17        0.          0.15        0.17        0.          0.
   0.          0.          0.17        0.085     ]
 [ 0.          0.17        0.          0.17        0.15        0.          0.
   0.          0.          0.17        0.085     ]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.425       0.          0.085     ]
 [ 0.          0.17        0.          0.17        0.17        0.          0.
   0.15        0


Fetched 30 total friends ids for 214584456
Fetched 179 total followers ids for 214584456


now constructing graphs


Graph Construction for 89607427 is finished
Graph Construction for 582920886 is finished
Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Graph Construction for 314644422 is finished
Graph Construction for 136074467 is finished
Graph Construction for 177146312 is finished
Graph Construction for 267151229 is finished
Graph Construction for 3458659276 is finished
Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Graph Construction for 1720502701 is finished
Graph Construction for 3986186235 is finished
Encountered 401 Error (Not Authorized)
Graph Construction for 2385312112 is finished
Graph Construction for 214584456 is finished


[[ 0.15        0.28333333  0.28333333  0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.28333333  0.15        0.28333333  0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.28333333  0.          0.15        0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.15        0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.15        0.
   0.28333333  0.          0.425       0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.28333333  0.          0.          0.085     ]
 [ 0.          0.28333333  0.          0.425       0.          0.2125      0.15
   0.28333333  0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.2125      0.
   0.15        0


Fetched 7 total friends ids for 1864435375
Fetched 142 total followers ids for 1864435375


now constructing graphs


Graph Construction for 1317340518 is finished
Graph Construction for 1864435375 is finished


[[ 0.15  0.85]
 [ 0.85  0.15]]


Fetched 667 total friends ids for 244873413
Fetched 5000 total followers ids for 244873413


now constructing graphs


Graph Construction for 196415460 is finished
Graph Construction for 244873413 is finished


[[ 0.15  0.85]
 [ 0.85  0.15]]


Fetched 485 total friends ids for 63382216
Fetched 2266 total followers ids for 63382216


now constructing graphs


Graph Construction for 456819201 is finished
Graph Construction for 173358083 is finished
Graph Construction for 393014791 is finished
Graph Construction for 328311822 is finished
Graph Construction for 3241963024 is finished
Graph Construction for 332520536 is finished
Graph Construction for 217336340 is finished
Graph Construction for 3226677271 is finished
Graph Construction for 292678169 is finished
Graph Construction for 2640557083 is finished
Graph Construction for 63382216 is finished


[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.12142857  0.          0.085     ]
 [ 0.          0.15        0.          0.          0.          0.          0.
   0.          0.12142857  0.          0.085     ]
 [ 0.          0.          0.15        0.          0.          0.          0.
   0.          0.12142857  0.          0.085     ]
 [ 0.          0.          0.          0.15        0.          0.          0.
   0.          0.12142857  0.          0.085     ]
 [ 0.          0.          0.          0.          0.15        0.
   0.28333333  0.          0.12142857  0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.12142857  0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.15        0


Fetched 231 total friends ids for 608158960
Fetched 291 total followers ids for 608158960


now constructing graphs


Graph Construction for 1118011393 is finished
Graph Construction for 2453603593 is finished
Graph Construction for 163730859 is finished
Graph Construction for 2478913428 is finished
Graph Construction for 4127364148 is finished
Graph Construction for 1183728474 is finished
Graph Construction for 608158960 is finished


[[ 0.15        0.          0.          0.          0.          0.
   0.14166667]
 [ 0.          0.15        0.          0.          0.          0.
   0.14166667]
 [ 0.          0.          0.15        0.          0.          0.
   0.14166667]
 [ 0.          0.          0.          0.15        0.          0.
   0.14166667]
 [ 0.          0.          0.          0.          0.15        0.
   0.14166667]
 [ 0.          0.425       0.          0.          0.          0.15
   0.14166667]
 [ 0.85        0.425       0.85        0.85        0.85        0.85        0.15      ]]


Fetched 749 total friends ids for 267061023
Fetched 2772 total followers ids for 267061023


now constructing graphs


Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Graph Construction for 620884480 is finished
Graph Construction for 28391425 is finished
Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Graph Construction for 1683993602 is finished
Graph Construction for 2893157379 is finished
Graph Construction for 148492811 is finished
Graph Construction for 477435918 is finished
Encountered 401 Error (Not Authorized)
Graph Construction for 1597395288 is finished
Graph Construction for 2872809495 is finished
Graph Construction for 581162017 is finished
Graph Construction for 1952386092 is finished
Graph Construction for 267061023 is finished


[[ 0.15        0.          0.          0.          0.28333333  0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.          0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.15        0.          0.28333333  0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.15        0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.425       0.          0.425       0.          0.15        0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.15        0


Fetched 59 total friends ids for 945012014
Fetched 104 total followers ids for 945012014


now constructing graphs


Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Graph Construction for 3998637827 is finished
Graph Construction for 3039857925 is finished
Graph Construction for 3235289862 is finished
Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Graph Construction for 2185499015 is finished
Graph Construction for 4442804182 is finished
Graph Construction for 2282715027 is finished
Graph Construction for 3991075220 is finished
Encountered 401 Error (Not Authorized)
Graph Construction for 3387553685 is finished
Graph Construction for 3296136345 is finished
Graph Construction for 2317297306 is finished
Graph Construction for 945012014 is finished


[[ 0.15        0.14166667  0.12142857  0.          0.          0.          0.
   0.14166667  0.17        0.12142857  0.085     ]
 [ 0.28333333  0.15        0.12142857  0.2125      0.2125      0.          0.
   0.          0.          0.12142857  0.085     ]
 [ 0.          0.14166667  0.15        0.          0.          0.          0.
   0.          0.          0.12142857  0.085     ]
 [ 0.          0.14166667  0.          0.15        0.          0.28333333
   0.          0.          0.          0.12142857  0.085     ]
 [ 0.          0.14166667  0.12142857  0.          0.15        0.          0.
   0.14166667  0.          0.12142857  0.085     ]
 [ 0.          0.          0.          0.2125      0.          0.15        0.
   0.14166667  0.17        0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.          0.          0.085     ]
 [ 0.28333333  0.          0.12142857  0.          0.2125      0.28333333
   0.       


Fetched 214 total friends ids for 36063241
Fetched 578 total followers ids for 36063241


now constructing graphs


Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Graph Construction for 160840800 is finished
Graph Construction for 1040492736 is finished
Encountered 401 Error (Not Authorized)
Encountered 401 Error (Not Authorized)
Graph Construction for 81073859 is finished
Graph Construction for 3227735377 is finished
Graph Construction for 48904520 is finished
Graph Construction for 2590128396 is finished
Graph Construction for 11026992 is finished
Encountered 401 Error (Not Authorized)
Graph Construction for 20425521 is finished
Graph Construction for 50934900 is finished
Graph Construction for 40739351 is finished
Graph Construction for 36063241 is finished


[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.          0.28333333  0.          0.          0.
   0.          0.28333333  0.          0.085     ]
 [ 0.          0.          0.15        0.          0.          0.          0.2125
   0.          0.          0.          0.085     ]
 [ 0.          0.28333333  0.          0.15        0.          0.          0.
   0.          0.28333333  0.          0.085     ]
 [ 0.          0.          0.28333333  0.          0.15        0.          0.2125
   0.425       0.          0.28333333  0.085     ]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.28333333  0.          0.2125      0.          0.15
   0.          0.          0.28333333  0.085     ]
 [ 0.          0.          0.          0.          0.2125      0.          0.
   0.15 


Fetched 29 total friends ids for 428702574
Fetched 236 total followers ids for 428702574


now constructing graphs


Graph Construction for 3097447936 is finished
Graph Construction for 28739265 is finished
Graph Construction for 21596164 is finished
Graph Construction for 79488677 is finished
Graph Construction for 1184680934 is finished
Graph Construction for 14047207 is finished
Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Graph Construction for 309202664 is finished
Graph Construction for 62943292 is finished
Graph Construction for 26672522 is finished
Graph Construction for 53581965 is finished
Graph Construction for 428702574 is finished


[[ 0.15        0.          0.09444444  0.          0.          0.          0.
   0.12142857  0.          0.          0.085     ]
 [ 0.          0.15        0.          0.28333333  0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.28333333  0.          0.15        0.          0.          0.17        0.2125
   0.12142857  0.17        0.          0.085     ]
 [ 0.          0.425       0.09444444  0.15        0.          0.          0.2125
   0.          0.17        0.          0.085     ]
 [ 0.          0.          0.09444444  0.          0.15        0.17        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.09444444  0.          0.          0.15        0.
   0.12142857  0.17        0.          0.085     ]
 [ 0.          0.          0.09444444  0.28333333  0.          0.          0.15
   0.12142857  0.          0.          0.085     ]
 [ 0.28333333  0.          0.09444444  0.          0.          0.17        0.2125
   0


Fetched 304 total friends ids for 271601301
Fetched 521 total followers ids for 271601301


now constructing graphs


Graph Construction for 1198200750 is finished
Graph Construction for 2540852360 is finished
Graph Construction for 32455305 is finished
Graph Construction for 2598910988 is finished
Graph Construction for 2425446669 is finished
Graph Construction for 632766867 is finished
Graph Construction for 116302356 is finished
Graph Construction for 741414421 is finished
Graph Construction for 19537303 is finished
Graph Construction for 2495930520 is finished
Graph Construction for 271601301 is finished


[[ 0.15    0.      0.      0.      0.17    0.      0.      0.      0.      0.
   0.085 ]
 [ 0.      0.15    0.      0.      0.      0.      0.      0.      0.      0.
   0.085 ]
 [ 0.      0.      0.15    0.      0.      0.      0.      0.      0.      0.
   0.085 ]
 [ 0.      0.      0.      0.15    0.17    0.      0.2125  0.      0.
   0.2125  0.085 ]
 [ 0.2125  0.      0.      0.2125  0.15    0.      0.2125  0.      0.
   0.2125  0.085 ]
 [ 0.      0.      0.      0.      0.      0.15    0.      0.      0.      0.
   0.085 ]
 [ 0.2125  0.      0.      0.2125  0.17    0.      0.15    0.      0.
   0.2125  0.085 ]
 [ 0.      0.      0.425   0.      0.      0.      0.      0.15    0.      0.
   0.085 ]
 [ 0.      0.      0.      0.      0.      0.      0.      0.      0.15    0.
   0.085 ]
 [ 0.2125  0.      0.      0.2125  0.17    0.      0.2125  0.      0.      0.15
   0.085 ]
 [ 0.2125  0.85    0.425   0.2125  0.17    0.85    0.2125  0.85    0.85
   0.2125  0.15  ]]


Fetched 38 total friends ids for 15370140
Fetched 297 total followers ids for 15370140


now constructing graphs


Graph Construction for 7093352 is finished
Graph Construction for 84909450 is finished
Graph Construction for 362163114 is finished
Graph Construction for 19685520 is finished
Graph Construction for 120375096 is finished
Graph Construction for 138831189 is finished
Graph Construction for 2984479160 is finished
Graph Construction for 361548986 is finished
Encountered 401 Error (Not Authorized)
Graph Construction for 484968138 is finished
Graph Construction for 15370140 is finished


[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.          0.09444444]
 [ 0.          0.15        0.          0.          0.          0.          0.
   0.          0.          0.09444444]
 [ 0.          0.          0.15        0.28333333  0.          0.          0.
   0.          0.          0.09444444]
 [ 0.          0.          0.28333333  0.15        0.          0.          0.
   0.425       0.          0.09444444]
 [ 0.          0.          0.          0.          0.15        0.          0.
   0.          0.425       0.09444444]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.09444444]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.          0.09444444]
 [ 0.          0.          0.28333333  0.28333333  0.          0.          0.
   0.15        0.          0.09444444]
 [ 0.          0.          0.          0.          0.425     


Fetched 43 total friends ids for 432500173
Fetched 168 total followers ids for 432500173


now constructing graphs


Graph Construction for 1436882689 is finished
Graph Construction for 531799722 is finished
Graph Construction for 451116492 is finished
Graph Construction for 354708653 is finished
Graph Construction for 249178415 is finished
Graph Construction for 2268100688 is finished
Encountered 429 Error (Rate Limit Exceeded)
Retrying in 15 minutes...ZzZ...
...ZzZ...Awake now and trying again.
Graph Construction for 248262289 is finished
Graph Construction for 1965371060 is finished
Graph Construction for 87154922 is finished
Graph Construction for 432500173 is finished


[[ 0.15        0.17        0.          0.          0.          0.          0.
   0.          0.          0.09444444]
 [ 0.425       0.15        0.28333333  0.425       0.28333333  0.          0.
   0.          0.          0.09444444]
 [ 0.          0.17        0.15        0.          0.          0.          0.
   0.          0.          0.09444444]
 [ 0.          0.17        0.28333333  0.15        0.          0.          0.
   0.          0.          0.09444444]
 [ 0.          0.17        0.          0.          0.15        0.          0.
   0.          0.425       0.09444444]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.09444444]
 [ 0.          0.          0.          0.          0.          0.          0.15
   0.          0.          0.09444444]
 [ 0.          0.          0.          0.          0.          0.          0.
   0.15        0.          0.09444444]
 [ 0.          0.          0.          0.          0.28333333


Fetched 46 total friends ids for 371513766
Fetched 248 total followers ids for 371513766


now constructing graphs


Graph Construction for 622077958 is finished
Graph Construction for 333722022 is finished
Graph Construction for 213017511 is finished
Graph Construction for 34613288 is finished
Graph Construction for 4244941575 is finished
Graph Construction for 380615661 is finished
Graph Construction for 1496536368 is finished
Graph Construction for 1258363284 is finished
Graph Construction for 393787000 is finished
Graph Construction for 2206803322 is finished
Graph Construction for 371513766 is finished


[[ 0.15        0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.15        0.2125      0.          0.          0.          0.
   0.2125      0.          0.          0.085     ]
 [ 0.          0.28333333  0.15        0.          0.          0.          0.17
   0.          0.28333333  0.          0.085     ]
 [ 0.          0.          0.          0.15        0.          0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.15        0.          0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.          0.          0.          0.15        0.
   0.          0.          0.          0.085     ]
 [ 0.          0.          0.2125      0.          0.          0.          0.15
   0.2125      0.28333333  0.28333333  0.085     ]
 [ 0.          0.28333333  0.          0.          0.          0.          0.17
   0.15     

In [247]:
result

{15370140: array([ 0.31689087,  0.31689087,  0.63364094,  0.95040418,  0.63386536,
         0.31689087,  0.31689087,  0.84481643,  0.63386536,  2.8516337 ]),
 22793219: array([ 0.08919265,  0.08919265,  0.08919265,  0.13378233,  0.08919265,
         0.17837631,  0.08919265,  0.08919265,  0.17837631,  0.08919265,
         0.89180995]),
 36063241: array([ 0.07306214,  0.21946186,  0.14456742,  0.21946186,  0.35036903,
         0.07306214,  0.28613792,  0.16061962,  0.21946186,  0.2321249 ,
         0.73059143]),
 43112027: array([  3.3155921 ,   3.3155921 ,   3.3155921 ,   3.3155921 ,
          3.3155921 ,  16.57588564]),
 63382216: array([ 0.27961617,  0.27961617,  0.27961617,  0.27961617,  0.3728322 ,
         0.15728224,  0.27961617,  0.15728224,  0.85639618,  0.15728224,
         1.57300899]),
 158434306: array([ 0.25275788,  0.40442868,  0.25275788,  0.37915845,  0.40442868,
         0.45498927,  0.25275788,  0.25275788,  0.25275788,  0.25275788,
         2.52794761]),
 214584456: a

### to show the scores for users

In [246]:
[{i:result[i][len(result[i])-1]} for i in result.keys()]

[{559720576: 1.6235608660175267},
 {778984993: 0.65439960759858029},
 {158434306: 2.5279476114235875},
 {22793219: 0.89180994765109967},
 {267061023: 1.5433445200186386},
 {1527529573: 0.53305398677515903},
 {371513766: 1.4977202314577818},
 {214584456: 1.7851963114870311},
 {246846985: 21.566038890615488},
 {271601301: 0.47122336258484748},
 {945012014: 0.32261406236558482},
 {570093647: 15.461064539444228},
 {608158960: 0.60464346252655898},
 {63382216: 1.5730089917560031},
 {428702574: 1.8956403562360387},
 {36063241: 0.73059142861020065},
 {432500173: 1.2266818901642089},
 {43112027: 16.57588563999348},
 {15370140: 2.8516337010427515},
 {1864435375: 10.071428571428571},
 {244873413: 171.35510510510511}]

In [267]:
users =[i for i in result.keys()]
users

[559720576,
 778984993,
 158434306,
 22793219,
 267061023,
 1527529573,
 371513766,
 214584456,
 246846985,
 271601301,
 945012014,
 570093647,
 608158960,
 63382216,
 428702574,
 36063241,
 432500173,
 43112027,
 15370140,
 1864435375,
 244873413]

In [270]:
twitter_api.users.lookup(user_id = 559720576)


[{u'contributors_enabled': False,
  u'created_at': u'Sat Apr 21 17:08:04 +0000 2012',
  u'default_profile': False,
  u'default_profile_image': False,
  u'description': u'Le jeu touche \xe0 sa fin.',
  u'entities': {u'description': {u'urls': []}},
  u'favourites_count': 2527,
  u'follow_request_sent': False,
  u'followers_count': 1149,
  u'following': False,
  u'friends_count': 255,
  u'geo_enabled': True,
  u'has_extended_profile': True,
  u'id': 559720576,
  u'id_str': u'559720576',
  u'is_translation_enabled': False,
  u'is_translator': False,
  u'lang': u'fr',
  u'listed_count': 7,
  u'location': u'District 12',
  u'name': u'Jos\xe9phine',
  u'notifications': False,
  u'profile_background_color': u'EDECE9',
  u'profile_background_image_url': u'http://pbs.twimg.com/profile_background_images/532120100/m_pokora_love_2.jpg',
  u'profile_background_image_url_https': u'https://pbs.twimg.com/profile_background_images/532120100/m_pokora_love_2.jpg',
  u'profile_background_tile': False,
  u'

In [268]:
user_info  = twitter_api.users.lookup(user_id = users,count = 100)
user_names = [{u['screen_name']:u['id']} for u in user_info]
user_names

[{u'fedescarabino': 778984993},
 {u'WELCHinc': 158434306},
 {u'mariagraciav': 22793219},
 {u'Musasdeldeporte': 267061023},
 {u'YTenoso': 1527529573},
 {u'YeisonAM': 371513766},
 {u'MedouneSambe': 214584456},
 {u'MarmaraForum': 246846985},
 {u'HardRockBrandi': 271601301},
 {u'garrettwallace_': 945012014},
 {u'li4mst3w4rt': 570093647},
 {u'haceratasoy': 608158960},
 {u'bicksoy': 63382216},
 {u'WestlakeHoops': 428702574},
 {u'RebeccaLiuow': 36063241},
 {u'leosouza1_': 432500173},
 {u'Etouns': 43112027},
 {u'BryanThistle': 15370140},
 {u'DeniseBerndt16': 1864435375}]

In [261]:
 twitter_api.users.lookup(user_id = 63382216)

[{u'contributors_enabled': False,
  u'created_at': u'Thu Aug 06 05:26:46 +0000 2009',
  u'default_profile': False,
  u'default_profile_image': False,
  u'description': u'R.i.p. Kahler & EJ',
  u'entities': {u'description': {u'urls': []},
   u'url': {u'urls': [{u'display_url': u'youtube.com/channel/UCLWbB\u2026',
      u'expanded_url': u'https://www.youtube.com/channel/UCLWbB0Ee07Tn9rz0UIvTGPg',
      u'indices': [0, 23],
      u'url': u'https://t.co/a7oVALnSMq'}]}},
  u'favourites_count': 4706,
  u'follow_request_sent': False,
  u'followers_count': 2267,
  u'following': False,
  u'friends_count': 485,
  u'geo_enabled': True,
  u'has_extended_profile': False,
  u'id': 63382216,
  u'id_str': u'63382216',
  u'is_translation_enabled': False,
  u'is_translator': False,
  u'lang': u'en',
  u'listed_count': 6,
  u'location': u'hiding',
  u'name': u'2ac\u1e96a\u1e5f\u024f',
  u'notifications': False,
  u'profile_background_color': u'000000',
  u'profile_background_image_url': u'http://pbs.twim

In [128]:
fraction = 0.7
matrix = pd.DataFrame.as_matrix(trimmed) * fraction
np.diag(matrix) = 1 - fraction
ranks = np.linalg.inv(np.transpose(matrix) -  numpy.eye(matrix.shape[0])).dot(np.transpose(matrix).dot(vector))
ranks - min(ranks)
prank = sl.eigs(np.transpose(matrix),k=1,sigma=1)

*------------------------

#Bonus Question: Prepare a 90 second Pitch and *present* it in the class (10 points)

* Prepare the slides for the Pitch (5 points)
* Present it in the class before your 10-minute talk (5 points).



*-----------------
# Done

All set! 

** What do you need to submit?**

* **Notebook File** (60 points): Save this IPython notebook.


* **PPT Slides** (20 points): please prepare PPT slides (for 10 minutes' talk) to present about the case study . 

* ** Report** (20 points): please prepare a report (less than 10 pages) to report what you did in this project.

     (please include figures or tables in the report, but no source code)

Please compress all the files in a zipped file.
